name: test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - pip
  - numpy
  - scipy
  - pandas
  - trackpy
  - networkx
  - scikit-learn
  - scikit-image
  - ffmpeg
  - sk-video
  - pytest
  - pytest-cov
