channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - blas=1.0
  - blosc=1.21.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - coverage=6.3.2
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - ffmpeg=4.3.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - fsspec=2022.3.0
  - giflib=5.2.1
  - icc_rt=2019.0.0
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - networkx=2.7.1
  - numexpr=2.8.1
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.2
  - partd=1.2.0
  - pillow=9.3.0
  - pip=22.3.1
  - pluggy=1.0.0
  - py=1.11.0
  - pyparsing=3.0.4
  - pytest=7.1.2
  - pytest-cov=4.0.0
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - six=1.16.0
  - sk-video=1.1.10
  - snappy=1.1.9
  - sqlite=3.40.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=1.2.2
  - toolz=0.11.2
  - trackpy=0.5.0
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.4.9
