name: sarcgraph-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg=4.2.2
  - matplotlib=3.5.2
  - networkx
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - python
  - scikit-image
  - scikit-learn
  - scipy
  - sk-video
  - trackpy
