on:
  push:
    paths:
      - '**.py'

jobs:
  check-py-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Format Python files with Black
        run: black --check .
      - name: Lint Python files with Flake8
        run: flake8