name: Tests
on: [push]

jobs:
  test:
    name: Run Python Tests
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    
    - uses: FedericoCarboni/setup-ffmpeg@v2
    
    - name: Install Python dependencies
      run: |
        C:\Miniconda\condabin\conda.bat create --name sg2 --file environment.yml
        C:\Miniconda\condabin\conda.bat init powershell

    - name: Test with pytest
      run: |
        # Activate the base environment
        C:\Miniconda\condabin\conda.bat activate sg2
        pytest --exitfirst --verbose --failed-first --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true
