name: Tests
on: [push]

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:

    - uses: actions/checkout@v3

    - name: Set up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - name: Test with pytest
      run: |
        pwd
        ls
        pytest --exitfirst --verbose --failed-first --cov=src --cov-report=xml --disable-warnings
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true
